"""add age field to user

Revision ID: 654e91b8fab6
Revises: c9d888a336c6
Create Date: 2022-10-16 10:20:04.555904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654e91b8fab6'
down_revision = 'c9d888a336c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
